import {
  DropdownMenu as DropdownMenuRoot,
  DropdownMenuArrow,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from '@/components/shadcn/ui/dropdown-menu';

export const DropdownMenu = {
  Root: DropdownMenuRoot,
  CheckboxItem: DropdownMenuCheckboxItem,
  Content: DropdownMenuContent,
  Arrow: DropdownMenuArrow,
  Group: DropdownMenuGroup,
  Item: DropdownMenuItem,
  Label: DropdownMenuLabel,
  Portal: DropdownMenuPortal,
  RadioGroup: DropdownMenuRadioGroup,
  Separator: DropdownMenuSeparator,
  Trigger: DropdownMenuTrigger,
  RadioItem: DropdownMenuRadioItem,
  Shortcut: DropdownMenuShortcut,
  Sub: DropdownMenuSub,
  SubTrigger: DropdownMenuSubTrigger,
  SubContent: DropdownMenuSubContent,
};
